### ISSUE TITLE
Proper json for imaging-study with regard to accession number

### ISSUE THREAD

**Issue by gkustas** [fhircast/docs#46]
Which is correct? The FHIR spec shows an actual element named "accession", whereas the FHIRCast example simply has a single identifier. I suspect the FHIRCast example is wrong, that is, unintentional.

Example in FHIRCast.org:

"key": "study",
      "resource": {
        "resourceType": "ImagingStudy",
        "id": "8i7tbu6fby5ftfbku6fniuf",
        "uid": "urn:oid:2.16.124.113543.6003.1154777499.30246.19789.3503430045",
        "identifier": [
          {
            "system": "7678",
            "value": "185444"
          }
        ],

FHIR 3.0 specification:

  "resourceType" : "ImagingStudy",
  // from Resource: id, meta, implicitRules, and language
  // from DomainResource: text, contained, extension, and modifierExtension
  "uid" : "<oid>", // R!  Formal DICOM identifier for the study
  "accession" : { Identifier }, // Related workflow identifier ("Accession Number")
  "identifier" : [{ Identifier }], // Other identifiers for the study

**Comment by isaacvetter** [comment]
Hey @gkustas - 

It's very possible that I messed up some of the FHIR examples in the FHIRcast spec, the FHIR spec is definitely authoritative for FHIR resources. Thank you for taking the time to write this up!

I'm not certain that the example is *strictly* wrong. The [ImagingStudy](https://www.hl7.org/fhir/imagingstudy.html) resource has both optional `accession` and `identifier` elements.

Do we think we should update the example to include an accession number? Should that replace the identifier or supplement it? (If so, interested in submitting a PR?)

Isaac

**Comment by isaacvetter** [comment]
@gkustas - @ElliiotSilver [on zulip points out](https://chat.fhir.org/#narrow/stream/117-fhircast-github/subject/docs.20.2F.20Issue.20.2346.20Proper.20json.20for.20imaging-study.20with.20regar.2E.2E.2E) that in [FHIR release 2, the ImagingStudy resource](https://build.fhir.org/imagingstudy.html) collapses both accession and uid into identifier. 

We should probably update the FHIR examples to be r4-compatible, since we'll most likely be balloting FHIRcast when r4 is the the most recent version of FHIR. 

That said, we can still look at adding an additional identifier that's specifically intended to be an accession number, to this example.

Isaac

**Comment by isaacvetter** [comment]
Hey @gkustas - well, either you should check out zulip or Elliot should respond on github. 😄 

He answered your question on [this ticket's auto-generated zulip post](https://chat.fhir.org/#narrow/stream/117-fhircast-github/subject/docs.20.2F.20Issue.20.2346.20Proper.20json.20for.20imaging-study.20with.20regar.2E.2E.2E). 

I'm going to go ahead and close this ticket, but open a new one documenting that we should update all FHIR examples to be compatible with FHIR r4.

Isaac
